### ISSUE TITLE
Возможность выбора ПВЗ без выбора тарифа

### ISSUE THREAD

**Issue by zerefiks** [cdek-it/widget#12]
В предыдущих версиях виджета была возможность выбора ПВЗ без выбора тарифа
То есть, если клиенту не нужно знать стоимость доставки, а просто нужно выбрать ПВЗ, на котором он хочет забрать заказ.
Может это уже реализовано на текущей версии, просто не указано в документации?

**Comment by zerefiks** [comment]
Заметил в примерах такой вариант, который примерно отражает суть вопроса:
`
document.addEventListener('DOMContentLoaded', () => {
  new window.CDEKWidget({
    apiKey: 'f4e034c2-8c37-4168-8b97-99b6b3b268d7',
    defaultLocation: 'Новосибирск',
  });
});
`

Но хотелось бы уточнить, какой параметр отвечает за отключение функционала выбора тарифа и оставляет возможность просто выбрать ПВЗ?

**Comment by gloriusglo** [comment]
@zerefiks, не указывайте параметр `goods`, тогда показываются все ПВЗ.

**Comment by vermorag** [comment]
Дубликат #2

**Comment by zerefiks** [comment]
> @zerefiks, не указывайте параметр `goods`, тогда показываются ПВЗ без расчета тарифа.

если не передавать goods - отображаются ВСЕ ПВЗ на карте (включая те, которые в дальнейшем не смогут принять доставку из-за большого веса, например)

**Comment by gloriusglo** [comment]
> > @zerefiks, не указывайте параметр `goods`, тогда показываются ПВЗ без расчета тарифа.
> 
> если не передавать goods - отображаются ВСЕ ПВЗ на карте (включая те, которые в дальнейшем не смогут принять доставку из-за большого веса, например)

Тогда использовать настройки из #2
Но, не факт, что отобразятся и те ПВЗ, которые смогут принять ваш груз. Описал эту проблему в #11
Задал вопрос в ТП СДЭК, почему не у всех ПВЗ указаны параметры принимаего груза. Возможно это обозначает, что эти ПВЗ могут все )
