### ISSUE TITLE
Очень маленькие значки пвз

### ISSUE THREAD

**Issue by techalexx** [cdek-it/widget#16]
Добрый день.
Очень маленькие значки пвз на мобильных устройствах. Причем групповые - кружок с цифрой в принципе нормальные, а вот уже конечные на которые надо кликать прям крошечные, хочется увеличить раза в два минимум. Что можно подкрутить?

**Comment by vermorag** [comment]
Добрый день. Можете скриншот предоставить? В эмуляторе и на моем устройстве все достаточно крупно.

**Comment by techalexx** [comment]
![desktop](https://github.com/cdek-it/widget/assets/14972280/c79d9889-8f84-444b-8c4c-6f75210cf6a8)
![mobileChrome](https://github.com/cdek-it/widget/assets/14972280/4506a438-ef44-4617-b4d8-6f3a52cc942c)

**Comment by techalexx** [comment]
Еще я обратил внимание, что как и старые версии эта неправильно считает доставку.
1. Виджет не учитывает страховку - считает без нее. Но если вы отправляете от организации то без страховки отправить невозможно.
2. Нет возможности передать в виджет стоимость упаковки(чтобы тоже приплюсовал), как это сделано в виджете почты россии

Это конечно можно прибавить уже в событии onChoose, но тогда покупатель видит неправильную стоимость доставки в виджете. Могу создать отдельную issue

**Comment by Oihso** [comment]
> Это конечно можно прибавить уже в событии onChoose, но тогда покупатель видит неправильную стоимость доставки в виджете

Сам сталкивался с подобной проблемой. Решить это можно с помощью события `onCalculate` в виджете:
```JavaScript
onCalculate: function (tariffs, address) {
    // Для доставки до двери
    tariffs.door.forEach(function (value, index) {
        value.delivery_sum += 100; // Ваша наценка
    });

    // Для ПВЗ
    tariffs.office.forEach(function (value, index) {
        value.delivery_sum += 100; // Ваша наценка
    });
}
```

При добавлении наценки в `onCalculate` пользователю будет показана уже "правильная" цена доставки с наценкой, а не расчет самого СДЕКа

**Comment by techalexx** [comment]
Я так и сделал в старой версии, новую пока не осилил до конца. после unminify она выглядит конечно странно ))

Добавить типа того:
в список параметров
addedCost: ST().default(0)

и где-то в коде
ho("div", null, X(t.delivery_sum + **e.coreStore.params.addedCost**) + " " + X(e.coreStore.params.currency), 1)

**Comment by vermorag** [comment]
> ![desktop](https://private-user-images.githubusercontent.com/14972280/286699600-c79d9889-8f84-444b-8c4c-6f75210cf6a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjI4NTYsIm5iZiI6MTcwMTM2MjU1NiwicGF0aCI6Ii8xNDk3MjI4MC8yODY2OTk2MDAtYzc5ZDk4ODktOGY4NC00NDRiLThjNGMtNmY3NTIxMGNmNmE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE2NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOTc3MTZjNTI5MDFkNWQ0ODU4ZTVlNTI1MTViY2EyMTI3MGU5OTlhNjU4ZmE3Y2MxNTQ1NzE1YzYwMWJkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gc1PzhHmQd3JB7hS7OudvQ1psQ-tLCFqdtFYDf_bBh8) ![mobileChrome](https://private-user-images.githubusercontent.com/14972280/286699608-4506a438-ef44-4617-b4d8-6f3a52cc942c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjI4NTYsIm5iZiI6MTcwMTM2MjU1NiwicGF0aCI6Ii8xNDk3MjI4MC8yODY2OTk2MDgtNDUwNmE0MzgtZWY0NC00NjE3LWI0ZDgtNmYzYTUyY2M5NDJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE2NDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNzI2Njk2Nzg1MTliODU3MDMzMWEzMWE0ZWE4OGQzNDVkMDViNWMwNmU1MGFhN2VjZTZhOTAzOTdlMmY1YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HI1MTDg_NrR3h7WUJr8qpcMObiovypWoU4k_qfKaWFk)

У меня это вот так (размеры иконок одинаковые у пвз и у групп). Проверьте widget.cdek.ru. У меня подозрение, что это стили на сайте меняют отображение.
![photo_2023-11-30_23-43-17](https://github.com/cdek-it/widget/assets/25276845/8e661ebc-18b7-4bb4-b268-66498032d6d6)

**Comment by techalexx** [comment]
Да, прошу прощения. Это действительно стили перемешались. У меня откуда-то проявилось svg {max-height: 20px;}
Но вы конечно зря в виджете напрямую к svg привязались, мало ли у кого как. Спасибо!
Как насчет добавленной стоимости?

**Comment by vermorag** [comment]
Тоже самое можно сказать и про img тэг. "Зря его используете". Но выводить графику то все равно надо? К сожалению, полностью оградить от влияния внешних стилей на виджет возможности нет, ведь все находится на одной странице и в рамках одного проекта. Но уже оградили влияние виджета на остальной сайт.
По добавленной стоимости отвечу завтра. Если делать, то полноценное комплексное решение, когда можно будет использовать полноценные ценовые правила, как это появилось в последней версии модуля для вордпресс.

**Comment by techalexx** [comment]
Ну я выше примитивное решение написал, лично меня оно устраивает. А там уж как решите.
По скорости загрузки есть какие-нибудь возможности ускорить процесс? У меня загружается примерно 5-8 секунд, это конечно много. Виджет почты 1-2 загружается

**Comment by vermorag** [comment]
Можете предоставить профайлинг с метриками скорости загрузки? Меня интересует время загрузки виджета, время работы service.php и время рендера после получения данных.

**Comment by techalexx** [comment]
У меня маленький проект не обремененный профайлером.
Встроенный же в хром говорит что тупит service.php?type=PVZ&allowed_cod=true&is_handout=true&action=offices
Собственно запрос к https://api.cdek.ru/v2 выполняется минимум 4-5секунд(скриншот 1), вот здесь в service.php

switch ($this->requestData['action']) {
            case 'offices':
                $this->sendResponse($this->getOffices());

Скриншот 2 - добавил вывод Date.now в лог виджета, подтверждается тупняк на загрузке более 4 сек и 135ms на разбор
135ms на разбор данных это кстати тоже очень много, а у меня на секундочку проц 13900к на 5.8ггц

![02](https://github.com/cdek-it/widget/assets/14972280/1b317dfb-907b-40f8-846d-354d4a53f5a7)
![01](https://github.com/cdek-it/widget/assets/14972280/161ed3d7-a51a-41ab-9cb3-4635a209a3b1)

**Comment by vermorag** [comment]
>По добавленной стоимости отвечу завтра. 

Поскольку проблема не является критичной, обращений подобной тематики зарегистрировано мало, с 18.12.2023 по 10.01.2023 в компании СДЭК вводится запрет на выкладку новых версий модулей - данный запрос поставлен в план разработки на 1Q.2024. В случае увеличения количества обращений по данному вопросу - срок может быть пересмотрен.

**Comment by vermorag** [comment]
> Собственно запрос к https://api.cdek.ru/v2 выполняется минимум 4-5секунд(скриншот 1), вот здесь в service.php

К сожалению, тут пока решения в голову не приходит. Там 4.5к+ точек, которые надо обработать (поэтому и 100ms). Сам запрос пока ускорить возможности нет.
Как обходное решение - передавать точки в виджет изначально (уже реализовано) или сделать ограничение по конкретному городу (в плане на 1Q.2024). Но тогда кроме этого города виджет больше ничего не покажет. Если же нужна вся РФ, то пока придется жить так. В 2-3Q.2024 будет проводится оптимизация api для виджета и CMS, возможно данный вопрос получится разрешить.

**Comment by techalexx** [comment]
В общем сделал так: по крону каждый час дергаю данные с https://api.cdek.ru/v2, сохраняю в файл.
А service.php теперь забирает из этого файла. Время выполнения 17мс

**Comment by vermorag** [comment]
> В общем сделал так: по крону каждый час дергаю данные с https://api.cdek.ru/v2, сохраняю в файл. А service.php теперь забирает из этого файла. Время выполнения 17мс

Достаточно проверять раз в день. Новые данные гарантированно не появляются чаще.

**Comment by vermorag** [comment]
>это бы уменьшило передаваемые данные раз в 5, может побыстрее стало бы

Это время ответа сервера, а не передачи данных по сети. На каскаде видно, что как раз большую часть занимает обработка на сервере, а передача составляет лишь небольшой процент и за ее счет большой прибавки не выиграть.
![изображение](https://github.com/cdek-it/widget/assets/25276845/9d92262d-7fbe-4a70-8f03-27f0de6ee224)
