### ISSUE TITLE
Долгая загрузка виджета

### ISSUE THREAD

**Issue by diidon** [cdek-it/widget#18]
Карта стала очень долго загружаться. Бывает, что больше минуты идет загрузка.

Пробовали виджет версии V2.0 - всё работает быстро и моментально

**Comment by vermorag** [comment]
Для изучения инцидента прошу предоставить результаты профайлинга загрузки. Также можете обратить внимание на обсуждение в https://github.com/cdek-it/widget/issues/16#issuecomment-1834429460.

**Comment by kaavain** [comment]
> Для изучения инцидента, прошу предоставить результаты профайлинга загрузки. Также можете обратить внимание на обсуждение в [#16 (comment)](https://github.com/cdek-it/widget/issues/16#issuecomment-1834429460). ![image](https://private-user-images.githubusercontent.com/25276845/288603663-41c5e232-539e-4536-b8b6-fd11f07d1195.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDA2NTgsIm5iZiI6MTcwMjA0MDM1OCwicGF0aCI6Ii8yNTI3Njg0NS8yODg2MDM2NjMtNDFjNWUyMzItNTM5ZS00NTM2LWI4YjYtZmQxMWYwN2QxMTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyNTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNmJkNTFkMDJlZjRiMTEwZWM4MDNkODdmYmE3ODcwYjFjNmY4YzU2NzliMGRhYTY1MWZkMDI1MjFmY2E1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BsCHqKw-ftlKgj1eqQNbAOdnDyIomnvM40Rq0FTI9C4) Для сравнения - в Chrome widget.cdek.ru загружается вместе с виджетом за чуть меньше, чем 4 секунды, 2.88 из которых занимает запрос к service.php для получения списка офисов. Используемая скоростная конфигурация канала - до 100мбит ![image](https://private-user-images.githubusercontent.com/25276845/288604535-fb29b694-14df-43f0-ac32-12ea06447dc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNDA2NTgsIm5iZiI6MTcwMjA0MDM1OCwicGF0aCI6Ii8yNTI3Njg0NS8yODg2MDQ1MzUtZmIyOWI2OTQtMTRkZi00M2YwLWFjMzItMTJlYTA2NDQ3ZGMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDEyNTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMGZiZTcwYjZjODM5NmUzMTY4NTBkZjlkNWY2ZTBlMDYwNjk5MGNiMzZhMDdhMTk2N2I1ODhhNDQyMjhjMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zEm08wrROtJzlKHf3c0Y1xZ12H_URWMrXfEX5xte9Hc)

Вы можете приводить сколь угодно много красивых и убедительных примеров с цифрами и графиками. Но факт налицо:

ДО выхода последнего релиза карта всегда грузилась за 1-4 секунды, то есть разумное время. ПОСЛЕ (однако это не значит ВСЛЕДСТВИЕ) выхода релиза карта фактически не грузится совсем - я постоянно ищу ПВЗ и могу сказать, что за последние три дня если карта загрузилась за 10 секунд - это просто счастье какое-то, потому что в большинстве случаев это 1-2-3 МИНУТЫ, а нередко и просто ошибка, логи которой я приводил.

Вот например сейчас, 16:02 по Москве. Дождаться загрузки не могу.

**Comment by vermorag** [comment]
В момент долгой загрузки прошу выполнить на сервере команды 
```
curl 2ip.ru 
curl api.cdek.ru
dig api.cdek.ru +short
ping -c10 api.cdek.ru
traceroute api.cdek.ru
tracepath api.cdek.ru
mtr -rw -c10 -b api.cdek.ru
mtr --tcp -rw -c10 -b api.cdek.ru
mtr --udp -rw -c10 -b api.cdek.ru
```
И предоставить результат их выполнения.

**Comment by kaavain** [comment]
Предлагаю закрыть, судя по всему были временные трудности. Последние дни тормозов не наблюдается.
