### ISSUE TITLE
Возможность быстрой фильтрации ПВЗ по адресу на выбранной области карты

### ISSUE THREAD

**Issue by diidon** [cdek-it/widget#19]
В версии 2.x реализован фильтр ПВЗ по адресу таким вот образом:
![Screenshot_1](https://github.com/cdek-it/widget/assets/125272460/025669fd-52fe-4a24-b34c-bc3e3b98902a)
Если открыть область карты большого города (например - Москва), то при открытии списка ПВЗ можно начать вводить адрес ПВЗ и он быстро найдет нужный ПВЗ в выбранной области карты.
В новых же версиях - такое возможно, судя по всему, только через основной поиск, что очень неудобно и долго (поиск может длиться секунд 10 и куда удобнее, видя карту города - найти нужный пвз быстро просто введя адрес)

**Comment by vermorag** [comment]
Поиск ПВЗ по адресу/коду/наименованию в рамках выбранной области выполняется почти моментально (в зависимости от используемого окружения), поскольку не требует дополнительных запросов к серверам.
![image](https://github.com/cdek-it/widget/assets/25276845/c6661dfc-db4c-40ae-9ee5-6c6882c11f13)
![image](https://github.com/cdek-it/widget/assets/25276845/9fe1cb3f-29ad-4029-9f63-ad6e5ace61aa)
Соответственно, есть возможность выбрать ПВЗ не дожидаясь окончания поиска адреса/области.
