### ISSUE TITLE
Некритичные ошибки при инициализации с флагом popup: true

### ISSUE THREAD

**Issue by gvoskresenskii** [cdek-it/widget#27]
В консоле две ошибки на странице примера "Отображение виджета в режиме всплывающего окна"
https://widget.cdek.ru/examples/example3-3-3.html 

Не крашат скрипт, но немного смущают)

- Error: no element is specified to initialize PerfectScrollbar
- YandexMapException: <yandex-map> container is undefined after component mount. This is likely Vue Yandex Maps internal bug.

**Comment by DreamCloudProject** [comment]
![image](https://github.com/cdek-it/widget/assets/7961936/db6088b2-e7f4-4fc4-b1c2-4e498541230d)
<img width="1280" alt="image" src="https://github.com/cdek-it/widget/assets/7961936/336fda03-fae1-4fbe-8981-00960ac0cd9b">
Наблюдаю вот такую ситуацию. Яндекс Карты не инициализуются. 

Но я пробовал подключить Яндекс карты по ключу напрямую на другой странице, там я вижу Яндекс Карту.

Все запускаю у себя на локальном ПК, через веб-компонент в ShadowDOM. Вот исходный код компонента:

```javascript
import {MobxLitElement} from "@adobe/lit-mobx";
import {html} from "lit";
import "@cdek-it/widget";
import Widget from "@cdek-it/widget";
import {MscButton} from "../editor-components/MscButton.js";

export class BaseCdekWidget extends MobxLitElement {

    static properties = {
        widget : { type: Object, state: true  },
        item : { type: Object, state: true  },
        record : { type: Promise, state: true },
        theme: { type: String },
        languages : { type: Promise, state: true }
    }

    connectedCallback() {
        super.connectedCallback();

        this.widget = new Widget({
            root: 'cdek-map',
            apiKey: 'f610c41a-765e-487c-93d1-2f99dfade4bd',
            defaultLocation: [55.0415, 82.9346],
            servicePath: "/api/v1/cdek",
            popup: true,
            debug: true
        });
    }

    render() {
        return html`<div id="cdek-map" class="msm-cdek-widget" part="base">
            <msc-button theme="DARK" @click="${(e) => this.widget.open()}">Open Widget</msc-button>
        </div>`;
    }

}
```

**Comment by DreamCloudProject** [comment]
Я прописал алиас в hosts для HTTP referrer и на строне Яндекс, и все заработало

**Comment by vermorag** [comment]
В [3.9.7](https://github.com/cdek-it/widget/releases/tag/v3.9.7) не вижу больше этих предупреждений
