### ISSUE TITLE
Небольшой баг верстки попапа с табами "в пункт выдачи"/"до двери"

### ISSUE THREAD

**Issue by gvoskresenskii** [cdek-it/widget#28]
Карта немного вылезает за пределы попапа внизу, когда есть табы с выбором "пункт выдачи"/"до двери" (т.к. у обертки карты height: 100%), и крестик оказывается поверх этих табов.

(замечено в примере https://widget.cdek.ru/examples/example3-3-3.html)

<img width="1192" alt="image" src="https://github.com/cdek-it/widget/assets/50996659/c7854d63-8f18-493b-9935-3695e3cde777">

**Comment by vermorag** [comment]
Исправлено в [3.8.2](https://github.com/cdek-it/widget/releases/tag/v3.8.2)
