### ISSUE TITLE
Не ограничивает пользователей в выборе доставки курьером, хотя она отключена в настройках виджета

### ISSUE THREAD

**Issue by zerefiks** [cdek-it/widget#29]
Заметили, что пользователи все равно могут выбрать доставку курьером до адреса, хотя она отключена при настройке виджета:
`
hideDeliveryOptions: {
 office: false,
 door: true,
},
`
https://youtu.be/Kn6fIQtgz9U

Ограничить обработку события выбора доставки "До двери" то можем, но вот буд-то этого окошка с выбором доставки быть не должно у пользователей вообще. Да и кнопка "Выбрать" все равно активна будет у пользователей - виджет некорректно отработает

**Comment by vermorag** [comment]
Судя по приведенному видео, используется старая версия виджета. Необходимо обновиться до последней.
