### ISSUE TITLE
CSS виджета ломает верстку на сайте

### ISSUE THREAD

**Issue by AndreyVasilkov** [cdek-it/widget#3]
Добрый день.

При внедрении виджета v3.0 на страницу добавляются стили 
audio, canvas, embed, iframe, img, object, svg, video {
    display: block;
    vertical-align: middle;
}

картинки которые раньше были инлайн элементами теперь на всей странице рвут строчку. 
зачем в стилях использовать общие css для виджета, который предусматривает интеграцию в существующую страницу html? Можете это исправить?

**Comment by vermorag** [comment]
Данная особенность прописана в [требованиях](https://github.com/cdek-it/widget/blob/main/docs/ru/INTRO.md#%D1%81%D0%BE%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C-%D1%81-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%BC%D0%B8-%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B0%D0%BC%D0%B8-%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D0%B5-%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F) - сайт должен быть совместим с технологией normalize.css.
Однако в версии 3.6 был изменен используемый CSS фреймворк, что может разрешить данный вопрос.
