### ISSUE TITLE
Ошибка при загрузке виджета

### ISSUE THREAD

**Issue by aeyoa** [cdek-it/widget#35]
### Ситуация
Есть headless [сайт](https://badgallery.com/) на [Next.js](https://nextjs.org/). Бэкенд сделан на [Kirby CMS](https://getkirby.com/). На сайте есть небольшой интернет-магазин. Пытаюсь интегрировать туда виджет для расчета стоимости доставки и выбора адреса. 

### Проблема
На тестовом API (https://api.edu.cdek.ru/v2) и с тестовыми ключами получилось все наладить. Несколько дней назад попробовали перейти на боевое API и настоящие ключи и — виджет перестал открываться. Выглядит это так: 

![Screenshot 2024-02-23 at 19 02 36](https://github.com/cdek-it/widget/assets/6937970/d5ff221b-2fdf-46e0-ad66-c078262bc927)

### Возможные причины
В попытках разобраться обнаружил, что поведение виджета на этом сайте отличается от ожидаемого поведения. Чистая минимальная установка виджета работает так: 

![Screenshot 2024-02-23 at 19 06 10](https://github.com/cdek-it/widget/assets/6937970/973f1652-9e85-4e05-b61f-0e37c64a04e9)

На скриншоте видно, что скрипт отправляет 16 запросов вида `?is_handout=true&action=offices&page=15&size=500`. Ответ на каждый запрос весит в районе 120 кб (что и так довольно много), но все ответы приходят и виджет открывается. 

Для чистоты эксперимента сделал новый проект на Next.js и засетапил в нем такой же минимальный код виджета. По каким-то необъяснимым причинам в таких условиях виджет отправляет аналогичный запрос, но без параметра `size=500`. Результат — огромный ответ от сервера иногда до 15 МБ (!!!), который роняет пребек (на [next api routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)) и виджет не открывается. Запрос видно на скриншоте: 

![Screenshot 2024-02-23 at 19 14 41](https://github.com/cdek-it/widget/assets/6937970/eab082a0-beca-47b1-a24c-0ed4b78fe2d8)

Аналогичный запрос напрямую к серверу service.php выдает ошибку. Пару раз возвращался ответ гигантского размера (больше 10 МБ, что абсолютно неприемлемо в любом случае).

![Screenshot 2024-02-23 at 19 17 27](https://github.com/cdek-it/widget/assets/6937970/d09d90f1-9929-4ef8-a804-afc730a2a81a)

### Возможное решение
Убедиться, что виджет всегда отправляет запрос с лимитом `size=500`. 

### Код, чтобы воспроизвести ошибку: 

1. Делаем новый проект на next.js `npx create-next-app@latest`. В качетсве роутера выбираем **pages router**
2. pages/index.js:
```js
import Script from "next/script"
import { useState } from "react"

export default function test(params) {
  const [widget, setWidget] = useState()

  function initCDEK() {
    setWidget(
      new window.CDEKWidget({
        from: "Санкт-Петербург",
        root: "cdek-map",
        apiKey: "ключ от яндекс карт",
        servicePath: "http://localhost:3001/api/service",
        defaultLocation: "Санкт-Петербург",
        popup: true,
      })
    )
  }
  return (
    <div>
      <Script src="https://cdn.jsdelivr.net/npm/@cdek-it/widget@3" onReady={initCDEK} />
      <button
        onClick={() => {
          widget.open()
        }}>
        Open widget
      </button>
    </div>
  )
}

```
3. Файл pages/api/service.js (пребек):
```js
import axios from "axios"

export default function handler(request, response) {
  if (request.method === "GET") {
    try {
      axios({
        method: "GET",
        url: `https://api.badgallery.com/api/cdek/service`,
        params: request.query,
      })
        .then(res => {
          response.status(200).json(res.data)
        })
        .catch(error => {
          response.status(500).json(error)
          console.log(error)
        })
    } catch {
      response.status(500).json({ error: "request failed" })
    }
  } else if (request.method === "POST") {
    try {
      axios
        .request({
          method: "POST",
          url: `https://api.badgallery.com/api/cdek/service`,
          data: request.body,
        })
        .then(res => {
          response.status(200).json(res.data)
        })
        .catch(error => {
          response.status(500).json(error)
          console.log(error)
        })
    } catch {
      response.status(500).json({ error: "request failed" })
    }
  } else {
    // This handler doesn't handle anything but GET request
    response.status(500).json({ error: "Not handled" })
  }
}

```

По адресу https://api.badgallery.com/api/cdek/service запускается скрипт `service.php` к рабочими ключами из ЛК.

**Comment by aeyoa** [comment]
[Ссылка на демо](https://bad-gallery-pvhq2jcou-std-aeyoa.vercel.app/shop/cart), где можно посмотреть, как виджет не работает онлайн :))

**Comment by vermorag** [comment]
Добрый день. 
> На скриншоте видно, что скрипт отправляет 16 запросов вида ?is_handout=true&action=offices&page=15&size=500. Ответ на каждый запрос весит в районе 120 кб (что и так довольно много), но все ответы приходят и виджет открывается.

>Результат — огромный ответ от сервера иногда до 15 МБ (!!!), который роняет пребек (на [next api routes](https://nextjs.org/docs/pages/building-your-application/routing/api-routes)) и виджет не открывается

С версии 3.9 как раз была реалзиована пагинация, чтобы не тянуть весь объем целиком. С тестовой средой работает просто потому, что там представлены не все офисы из продовой среды, а значит объем меньше. Сократить его прямо сейчас возможности нет (этот вопрос обсуждался в [#34](https://github.com/cdek-it/widget/issues/34#issuecomment-1931214736)).

Отправка запроса с `?is_handout=true&action=offices&page=0` была реализована для обратной совместимости бэкендов виджета. На сколько вижу, пребэк реализован по мотивам версий до 3.9.
Как это рабоатет сейчас: виджет отправляет запрос на получение первой страницы и ожидает в ответ заголовки `x-current-page` и `x-total-pages`. Если их не пришло - считаем, что используется старый бэк и надо спрашивать 0 страницу со всеми офисами. Иначе вычисляем число страниц и запрашиваем каждую.

Соответственно, чтобы переключиться на новую версию бэкенда с пагинацией - необходимо прокидывать эти два нужных заголовка. Или вообще переписать бэкенд на JS (по факту - это ведь тот же прокси до апи2)

**Comment by ubzor** [comment]
Похоже, у меня эта же ошибка. На боевом апи script.php стал возвращать `Server not authorized to CDEK API`, хотя ещё неделю назад всё работало нормально. При переключении на тестовое апи ошибка исчезает.

**Comment by vermorag** [comment]
>На боевом апи script.php стал возвращать Server not authorized to CDEK API

С какой версией виджета?

**Comment by ubzor** [comment]
> > На боевом апи script.php стал возвращать Server not authorized to CDEK API
> 
> С какой версией виджета?

пробовал на 3.9.1 и 3.9.3

**Comment by vermorag** [comment]
>Пробовал на 3.9.1 и 3.9.3

А версия бэкенда от какого?

**Comment by ubzor** [comment]
> > Пробовал на 3.9.1 и 3.9.3
> 
> А версия бэкенда от какого?

script.php тех же версий

**Comment by KenostDeveloper** [comment]
Такая же проблема, решение не найдено

**Comment by ubzor** [comment]
> Похоже, у меня эта же ошибка. На боевом апи script.php стал возвращать `Server not authorized to CDEK API`, хотя ещё неделю назад всё работало нормально. При переключении на тестовое апи ошибка исчезает.

Разобрались, оказывается менеджер в ЛК нажал на кнопку "обновить ключи" и старые стали недействительными 🤦‍♂️

**Comment by yuri-kovalev** [comment]
> > Похоже, у меня эта же ошибка. На боевом апи script.php стал возвращать `Server not authorized to CDEK API`, хотя ещё неделю назад всё работало нормально. При переключении на тестовое апи ошибка исчезает.
> 
> Разобрались, оказывается менеджер в ЛК нажал на кнопку "обновить ключи" и старые стали недействительными 🤦‍♂️

А можно пожалуйста узнать актуальные ключи? 
Те что указаны на странице документации не актуальны 
https://api-docs.cdek.ru/29923849.html

**Comment by vermorag** [comment]
> А можно пожалуйста узнать актуальные ключи? Те что указаны на странице документации не актуальны https://api-docs.cdek.ru/29923849.html

На странице документации указаны актуальные ключи от тестовой среды (api.edu.cdek.ru). Актуальные ключи от боевой среды вы можете посмотреть в вашем [личном кабинете](https://lk.cdek.ru/integration).

**Comment by yuri-kovalev** [comment]
> > А можно пожалуйста узнать актуальные ключи? Те что указаны на странице документации не актуальны https://api-docs.cdek.ru/29923849.html
> 
> На странице документации указаны актуальные ключи от тестовой среды (api.edu.cdek.ru). Актуальные ключи от боевой среды (api.cdek.ru) вы можете посмотреть в вашем [личном кабинете](https://lk.cdek.ru/integration).

Благодарю за ответ! А где можно прочитать что для тестовой среды нужно использовать другой url? И самое главное как мне это указать виджету? https://github.com/cdek-it/widget/wiki/Настройка-3.0
