### ISSUE TITLE
Неправильное отображение карты в виджете

### ISSUE THREAD

**Issue by nstrkrll** [cdek-it/widget#36]
Карта в виджете вылазит за границы родительского контейнера. 
Можно посмотреть здесь: https://widget.cdek.ru/ . Карта вылазит за границы родительского div id="cdek-map"

**Comment by vermorag** [comment]
На widget.cdek.ru вся карта находится в рамках своего родительского элемента. Прошу уточнить что имеется в виду.
![image](https://github.com/cdek-it/widget/assets/25276845/2919d787-e767-49e7-b4b2-67e4071fbb99)

**Comment by vermorag** [comment]
Исправлено в [3.9.7](https://github.com/cdek-it/widget/releases/tag/v3.9.7)
