### ISSUE TITLE
На карте для выбора ПВЗ пропали все ПВЗ РФ

### ISSUE THREAD

**Issue by zerefiks** [cdek-it/widget#38]
Буквально со вчерашнего дня на карте выбора ПВЗ, которая до этого работала исправно, пропали ПВЗ в РФ.
Отображается только 1 ПВЗ - в Казахстане
Абай, пр. Абая, 21
ABA1

**Comment by vermorag** [comment]
Необходимо обновить бэкенд часть (service.php) на актуальную.
