### ISSUE TITLE
Не отображаются все тарифы, которые приходят, и скролл не позволяет увидеть полностью те, что пришли

### ISSUE THREAD

**Issue by knilsyansky** [cdek-it/widget#39]
### Environment

- Версия браузера - Version 122.0.6261.111 (Official Build) (64-bit)
- Используется тестовое апи сдека. 
- Версия виджета - последняя 3 (3.9.5).
- Приложение на React.js 16.14.0

### Issue Description:

В нетворке приходит 14 тарифов, но в списке видно лишь 8 и в ДОМе видно тоже только 8 элементов в списке (и еще два технических элемента). На скриншотах положение скролла находится максимально внизу, но последний отрисованный элемент показывается лишь частично.

### Screenshots:

![image](https://github.com/cdek-it/widget/assets/60538599/75d8b0c7-9c8f-4cd5-97bf-e53140b68b28)
![image](https://github.com/cdek-it/widget/assets/60538599/85f5733d-42aa-49ff-aaf6-b18d9eacdb0d)

**Comment by knilsyansky** [comment]
Только сейчас обратил внимание, что в консоли есть сообщение о скролле в момент открытия виджета
![image](https://github.com/cdek-it/widget/assets/60538599/0d8f235d-113e-4308-8fd7-4005de1bc965)

**Comment by vermorag** [comment]
Исправлено в [3.9.7](https://github.com/cdek-it/widget/releases/tag/v3.9.7)
