### ISSUE TITLE
Кнопка Выбрать отправляет форму на странице

### ISSUE THREAD

**Issue by AndreyVasilkov** [cdek-it/widget#4]
Версия виджета 3.0
При нажатии на кнопку Выбрать, форма на текущей странице отправляется. Пробовали отменить событие click на кнопках - не помогло. Пробовали вынести код виджета за форму - не помогло. Подскажите, как не отправлять форму заказа, выбирая пункт самовывоза?

**Comment by vermorag** [comment]
К сожалению, это проблема яндекса - они выводят все кнопки управления тэгом button, однако не задают ему тип. отчего при нажатии на кнопки срабатывает сабмит формы. С нашей стороны добавил stopPropagation для кнопки выбора (войдет в релиз 3.6), однако управление масштабом и определение текущего местоположения по прежнему будут отправлять форму заказа. Это [стандартное поведение ](https://www.w3.org/TR/2011/WD-html5-20110525/the-button-element.html#the-button-element) кнопок, которые выводятся API яндекса, прямого доступа к нему мы не имеем.
![image](https://github.com/cdek-it/widget/assets/25276845/4961f3c5-ce4f-442a-b3a7-e7051cf13358)
По данному вопросу можете обратиться в яндекс через их форму обратной связи: https://yandex.ru/maps-api/feedback.

**Comment by vermorag** [comment]
Было найдено обходное решение. Будет выпущено в рамках ближайшего релиза.

**Comment by vermorag** [comment]
Закрыто в [3.8.0](https://github.com/cdek-it/widget/releases/tag/v3.8.0)
