### ISSUE TITLE
Не работает виджет, бесконечная загрузка

### ISSUE THREAD

**Issue by ivan-gru** [cdek-it/widget#40]
С 12.03 видеж перестал работать, со следующей ошабкой:
![photo_2024-03-15_11-46-11](https://github.com/cdek-it/widget/assets/163513740/1ae9c063-b3c2-4b57-8162-c2617c5c47f8)

Виджет установлен на сайте https://proflc.com/ можно увидеть если добавить товар в корзину и в корзине нажать кнопку "СДЭК".

**Comment by vermorag** [comment]
Судя по логам, используется версия виджета 2.0. Это репозиторий для версии 3+. Вторая версия больше не подддерживается и ее стабильная работа не гарантируется.
