### ISSUE TITLE
onCalculate не приходит адрес выбранного ПВЗ

### ISSUE THREAD

**Issue by gorasu** [cdek-it/widget#41]
onCalculate в качестве ответа не приходит адрес выбранного ПВЗ.

![image](https://github.com/cdek-it/widget/assets/4436611/f3c8e780-ae85-4a4a-a9c9-266ad2abed96)

При выборе тарифа onChange также не приходит адрес выбранного ПВЗ
![image](https://github.com/cdek-it/widget/assets/4436611/a1e755f6-2097-4997-bd0f-de787d09e716)

В документации описано что данные должны приходить, подскажите как получить адрес выбранного ПВЗ ?

**Comment by vermorag** [comment]
Адрес ПВЗ в onCalculate не передается. Обект адреса формируется следующим кодом:
```
            const address = {
                address: coreStorage.mode === DeliveryMode.DOOR ? mapStorage.pointInfo?.formatted : undefined,
                country_code: coreStorage.mode === DeliveryMode.DOOR ? mapStorage.pointInfo?.country_code : undefined,
                postal_code: coreStorage.mode === DeliveryMode.DOOR ? mapStorage.pointInfo?.postal_code : undefined,
                code: coreStorage.mode === DeliveryMode.OFFICE ? mapStorage.exactOffice?.city_code : undefined,
            };
```
