### ISSUE TITLE
Ломаются select и Textarea

### ISSUE THREAD

**Issue by Goalof** [cdek-it/widget#55]
В вашем виджете подключается файл https://cdn.jsdelivr.net/npm/@unocss/reset@0.58.5/tailwind.css
Который ломает Select и Textearea 

До: https://ukit.top/src/58/2024-04-08-21-55-54.png
После: https://ukit.top/src/58/2024-04-08-21-56-13.png

Поменяйте классы на свои

**Comment by Goalof** [comment]
Например я использую опции товаров в формате выбора select  и ваш виджет делает их тонькими и не привлекательными

**Comment by vermorag** [comment]
Добрый день.
Виджет устанавливается только через файл `https://cdn.jsdelivr.net/npm/@cdek-it/widget@3`. Никаких дополнительных внешних зависимостей он не имеет и не подключает их в процессе инициализации.
`https://cdn.jsdelivr.net/npm/@unocss/reset@0.58.5/tailwind.css` в нем не используется.
