### ISSUE TITLE
Раскрываемый список офисов пуст после инициализации

### ISSUE THREAD

**Issue by ubzor** [cdek-it/widget#62]
Если после инициализации виджета открыть список офисов справа, то он будет пустым, и начинает отображаться через несколько секунд после того как пользователь подвигает картой, неважно какой город был указан при инициализации. Наблюдать это поведение можно [здесь](https://widget.cdek.ru/) в свежих версиях Chrome и Firefox. Хотелось бы, чтобы при открытии списка офисов в нём была актуальная информация.

**Comment by vermorag** [comment]
Должно закрыться в [v3.10.1](https://github.com/cdek-it/widget/releases/tag/v3.10.1)
