### ISSUE TITLE
Баг в панели со списком офисов

### ISSUE THREAD

**Issue by ubzor** [cdek-it/widget#63]
Если открыть список офисов справа, пролистить его вниз на произвольное количество пикселей, нажать на какой-то случайный офис, и выбрать его, а после этого закрыть панель информации о выбранном офисе и ещё раз открыть список офисов - то он будет проскролен вниз на то самое произвольное количество символов, и если его прокрутить вверх - содержать в себе один выбранный офис. При этом выглядит это так как будто список пуст. Воспроизводится [здесь](https://widget.cdek.ru/).

**Comment by vermorag** [comment]
Должно закрыться в [v3.10.1](https://github.com/cdek-it/widget/releases/tag/v3.10.1)
