### ISSUE TITLE
Метод selectOffice открывает панель с информацией о выбранном офисе через раз

### ISSUE THREAD

**Issue by ubzor** [cdek-it/widget#64]
Как уже [было указано здесь](https://github.com/cdek-it/widget/discussions/61), при выполнении метода `selectOffice` через раз открывается-закрывается панель с информацией о выбранном офисе при выборе другого офиса, т.е. первый вызов `selectOffice` выбирает нужный офис и открывает панель с информацией о нём справа, второй вызов тоже выбирает нужный офис, но панель с информацией закрывается, и так далее.

**Comment by vermorag** [comment]
Добрый день, да, косяк. На днях выйдет исправление. Проблема том, что он каждый раз вызывает toggle (переключение) шторки без проверки на ее статус.

**Comment by vermorag** [comment]
Должно закрыться в [v3.10.1](https://github.com/cdek-it/widget/releases/tag/v3.10.1)
