### ISSUE TITLE
Вместо id используется class

### ISSUE THREAD

**Issue by piton-zel** [cdek-it/widget#68]
В инструкции к 3.x указано
```
root | string | "cdek-map" | **ID элемента**, куда будет помещен виджет. В случае отсутствия - данный элемент будет создан на странице
```
По факту имеем следующее
```
<div **class**="cdek-map" data-v-app="">
```

**Comment by vermorag** [comment]
Если виджет не находит элемент на странице, то он создает его с классом, для того, чтобы не ломать совместимость с уже размещенными на странице виджетами, тк элемент с ID на странице может быть только один.

**Comment by piton-zel** [comment]
Надо тогда об этом явно указать в инструкции, т.к. там сказано обратное, что если нет, то создадим и как следствие это вводит в заблуждение, а так по коду то я посмотрел уже, когда впал в ступор, что не могу найти созданный элемент виджетом по его id (как было указано в инструкции)
```
const el = window.document.getElementById(this.params.root);
    if (el === null) {
      this.div = window.document.createElement("div");
      this.div.className = this.params.root;
```
