### ISSUE TITLE
Некорректная работа виджета: отображение ПВЗ, на которые по итогу нельзя отправить груз согласно ЛК СДЕК

### ISSUE THREAD

**Issue by diidon** [cdek-it/widget#7]
Столкнулся с проблемой:
Добавляю товары, параметры с тарифами при настройке виджета специально не указываю, чтобы учитывались все возможные тарифы.
По итогу производится расчет доставки, виджет показывает, что всё хорошо.

Пытаюсь в ЛК оформить заказ средствами API на выбранный ПВЗ - ошибка "Некорректный заказ".
Попытался в ЛК оформить заказ вручную с такими же товарами и тарифом - обнаруживается, что выбрать данный ПВЗ для этой группы товаров нельзя (видимо, слишком большие по весу).

Получается, что карта говорит - сюда доставить можно, на деле же - доставка в данный ПВЗ груза оказывается невозможной

**Comment by vermorag** [comment]
Данная доработка запланирована на I квартал 2024 года.

**Comment by vermorag** [comment]
Исправлено в [3.7.0](https://github.com/cdek-it/widget/releases/tag/v3.7.0)
