### ISSUE TITLE
При активном фильтре по тарифам не скрываются точки на карте

### ISSUE THREAD

**Issue by qexyorg** [cdek-it/widget#71]
Если в фильтре разрешенных тарифов (tariffs.office) нет подходящих под условие, то точка на карте по прежнему будет отображаться, но выбрать ПВЗ будет нельзя. 

![изображение](https://github.com/cdek-it/widget/assets/3864361/d35d0bea-55a1-4972-9f73-dd39c1aabd3e)

**Comment by vermorag** [comment]
Данное поведение является ожидаемым. Требований скрывать пвз по результатам рассчета с карты нет, поскольку это не входит в флоу использования виджета.
