### ISSUE TITLE
Высота обрезается

### ISSUE THREAD

**Issue by NEOdinok** [cdek-it/widget#75]
Заметил, что при выключении выбора офис/дверь виджет обрезается в высоту.
В коде есть вот такой класс "cdek-32nljf" со значением высоты:
`height: calc(100% - 3.375rem) !important;`

Есть предположение, что вот эти 3.375rem нужны для кнопок офис/дверь, а без них у виджета остается пустое место 

Можно ли сделать виджету height: 100% для случая, когда в конфиге выключен выбор режима доставки по этим кнопкам ?

**Comment by NEOdinok** [comment]
<img width="1510" alt="height-100" src="https://github.com/user-attachments/assets/bf23f5ea-5bf5-4df6-85af-0cb64fdead56">

<img width="1512" alt="height-cut" src="https://github.com/user-attachments/assets/c5a35bd5-2fe9-42dc-b815-696c9153133b">

Приложил фото с обрезанным виджетом и как бы это выглядело с высотой 100%

**Comment by vermorag** [comment]
Добрый день. Да, пропустил этот момент. В ближайшее время выпустим фикс.

**Comment by vermorag** [comment]
Поправлено в [3.10.3](https://github.com/cdek-it/widget/releases/tag/v3.10.3)

**Comment by NEOdinok** [comment]
Спасибо! 🤝🤝🤝
