### ISSUE TITLE
Отключение отображения ПВЗ, на которые нельзя доставить груз

### ISSUE THREAD

**Issue by diidon** [cdek-it/widget#8]
Иногда встречается ситуация, что ПВЗ не может принять груз (ошибка "невозможно расчитать стоимость"). 
Добавьте возможность отключения отображения данных ПВЗ, если нет доступных тарифов.
Иначе получается, что клиент оформил большой заказ и хочет доставку, например, в Москву, где очень густо расположены ПВЗ.
По итогу ему приходится "прокликивать" все ПВЗ в поисках того, который покажет доступные тарифы

**Comment by vermorag** [comment]
Дубликат #7
