### ISSUE TITLE
Некорректная обработка клика по карте с дублированием расчета на доставку

### ISSUE THREAD

**Issue by Oihso** [cdek-it/widget#9]
### Проблема

При клике по карте для выбора какого-либо адреса виджет отправляет 2 запроса расчета в `service.php`, вместо одного. Это приводит к тому, что у части пользователей, особенно с медленным интернет-соединением, расчет может не произойти вовсе или понадобится очень долго ожидать расчета без какой-либо индикации работы виджета. На видео ниже видно поведение виджета с двумя запросами

![bandicam 2023-11-13 13-20-51-118](https://github.com/cdek-it/widget/assets/35115534/fe1c0054-36c5-45f2-b8cc-abe1b090f974)

Первый запрос всегда некорректен, т.к. переменная `to_location` всегда пустая, и отправляется непосредственно в момент клика, что приводит к сообщению об ошибке (`Не могу посчитать стоимость`) на стороне пользователя:

![Скриншот_1](https://github.com/cdek-it/widget/assets/35115534/cd9f4c8b-ff14-4fdd-9feb-f7f273cd2b49)

1 Запрос:
```JSON
{
  "currency": 1,
  "lang": "rus",
  "from_location": {
    "address": "Россия, Москва"
  },
  "to_location": {},
  "action": "calculate",
  "packages": [
    {
      "width": 12,
      "height": 12,
      "length": 100,
      "weight": 448.5
    }
  ]
}
```
1 Ответ:
```JSON
{
    "errors": [
        {
            "code": "v2_invalid_value_type",
            "message": "Invalid value type in [to_location] field"
        }
    ]
}
```

После того, как карта произвела геокодинг и вернула адрес, виджет производит второй запрос расчета, уже с действительными данными, что позволяет произвести расчет:

![Скриншот_2](https://github.com/cdek-it/widget/assets/35115534/83cf8d3f-1ba3-43bf-95f6-f3b384053eab)

2 Запрос:
```JSON
{
  "currency": 1,
  "lang": "rus",
  "from_location": {
    "address": "Россия, Москва"
  },
  "to_location": {
    "address": "Россия, Москва, Красная площадь, 1"
  },
  "action": "calculate",
  "packages": [
    {
      "width": 12,
      "height": 12,
      "length": 100,
      "weight": 448.5
    }
  ]
}
```

2 Ответ:
```JSON
{
    "tariff_codes": [
        {
            "tariff_code": 158,
            "tariff_name": "Забор груза дверь-склад",
            "tariff_description": "",
            "delivery_mode": 2,
            "delivery_sum": 390.0,
            "period_min": 1,
            "period_max": 1,
            "calendar_min": 1,
            "calendar_max": 1
        },
        {"..."},
        {
            "tariff_code": 368,
            "tariff_name": "Посылка склад-постамат",
            "tariff_description": "",
            "delivery_mode": 7,
            "delivery_sum": 190.0,
            "period_min": 1,
            "period_max": 1,
            "calendar_min": 1,
            "calendar_max": 1
        }
    ]
}
```

### Ожидаемое поведение

Виджет должен отправлять на запрос на расчет тогда и только тогда, когда получил адрес клика от карты. Т.е. должна присутствовать проверка на наличие адреса, по которому делается расчет до того, как отправляется запрос.

**Comment by vermorag** [comment]
Исправлено в [3.7.0](https://github.com/cdek-it/widget/releases/tag/v3.7.0)
